In [2]:
import pandas as pd
import numpy as np

In [14]:
elwha = pd.read_csv('C:/Users/andrewm4/Documents/MastersDatasets/Kirschbaum_Frontal_Periods/elwha_basin_fronts.csv')
hoh = pd.read_csv('C:/Users/andrewm4/Documents/MastersDatasets/Kirschbaum_Frontal_Periods/hoh_basin_fronts.csv')
queets = pd.read_csv('C:/Users/andrewm4/Documents/MastersDatasets/Kirschbaum_Frontal_Periods/queets_basins_front.csv')
quinalt = pd.read_csv('C:/Users/andrewm4/Documents/MastersDatasets/Kirschbaum_Frontal_Periods/quinalt_basin_fronts.csv')

In [42]:
drop_clmns = ('00','sum','1','XLONG', 'XLAT','Bains','basins','fid')

In [43]:
elwha_drop = elwha.loc[:,~elwha.columns.str.endswith(drop_clmns)]
hoh_drop = hoh.loc[:,~hoh.columns.str.endswith(drop_clmns)]
queets_drop = queets.loc[:,~queets.columns.str.endswith(drop_clmns)]
quinalt_drop = quinalt.loc[:,~quinalt.columns.str.endswith(drop_clmns)]

In [45]:
elwha_mean = elwha_drop.mean()
hoh_mean = hoh_drop.mean()
queets_mean = queets_drop.mean()
quinalt_mean = quinalt_drop.mean()

In [56]:
df_concat = pd.concat([elwha_mean, hoh_mean, queets_mean, quinalt_mean], axis=1)

In [57]:
df_concat

                 0          1          2          3
WF1_ave  12.160319  19.014398  19.606587  18.877813
WS1_ave  40.722938  60.620366  62.352357  58.431175
WF2_ave  12.256425  16.901697  19.809567  18.712360
WS2_ave  37.984468  30.331555  26.565553  25.202153
PF1_ave  13.714108  11.092297  11.160853  11.045003
WF3_ave  12.780675  18.827545  21.743244  18.944074
WS3_ave  23.641386  26.466125  28.415591  22.371555
PF2_ave   4.781512   3.852971   3.599412   3.268977
WF4_ave  20.972998  21.452102  27.481876  26.053756
WS4_ave  17.947575  19.363155  22.459712  22.735840
WF5_ave   4.015648   7.064160   7.689875   9.178997
WS5_ave  39.856396  39.350594  41.791242  40.701151
PF3_ave   9.761288   9.217239   7.398092   6.896059
PF4_ave  13.160666  11.856445  11.752913  10.768106
PF5_ave   1.964900   2.488251   2.857335   3.432151
WF6_ave   7.643233   9.507433   9.616902  12.271514
WS6_ave  22.072855  26.036430  25.832739  27.364992
PF6_ave   2.250192   3.437530   2.911677   2.633013
Basins         NaN        NaN        NaN        NaN

In [71]:
df_concat.rename(index={0:"Elwha", 1:'Hoh',2:'Queets',3:'Quinalt'})

                 0          1          2          3
WF1_ave  12.160319  19.014398  19.606587  18.877813
WS1_ave  40.722938  60.620366  62.352357  58.431175
WF2_ave  12.256425  16.901697  19.809567  18.712360
WS2_ave  37.984468  30.331555  26.565553  25.202153
PF1_ave  13.714108  11.092297  11.160853  11.045003
WF3_ave  12.780675  18.827545  21.743244  18.944074
WS3_ave  23.641386  26.466125  28.415591  22.371555
PF2_ave   4.781512   3.852971   3.599412   3.268977
WF4_ave  20.972998  21.452102  27.481876  26.053756
WS4_ave  17.947575  19.363155  22.459712  22.735840
WF5_ave   4.015648   7.064160   7.689875   9.178997
WS5_ave  39.856396  39.350594  41.791242  40.701151
PF3_ave   9.761288   9.217239   7.398092   6.896059
PF4_ave  13.160666  11.856445  11.752913  10.768106
PF5_ave   1.964900   2.488251   2.857335   3.432151
WF6_ave   7.643233   9.507433   9.616902  12.271514
WS6_ave  22.072855  26.036430  25.832739  27.364992
PF6_ave   2.250192   3.437530   2.911677   2.633013
Basins         NaN        NaN        NaN        NaN

In [74]:
df_concat.to_csv(r'C:/Users/andrewm4/Documents/MastersDatasets/Kirschbaum_Frontal_Periods/frontal_basin_averages.csv')